USE db_exam;

DELIMITER //

CREATE EVENT remove_deleted_users
	ON SCHEDULE
	EVERY 1 DAY
	STARTS (CURRENT_DATE + INTERVAL 1 DAY + INTERVAL 1 HOUR)
	DO
BEGIN
	DELETE FROM user
	WHERE DATE(created_at) = CURRENT_DATE();
END; //

DELIMITER ;